# Generated by Django 3.1.5 on 2021-05-08 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.category', verbose_name='Категория'),
        ),
    ]
