# Generated by Django 3.1.5 on 2021-05-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20210508_1526'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Serial',
        ),
    ]
