# Generated by Django 3.1.5 on 2021-05-10 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_reviewsserial_serialshots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='url',
            new_name='slug',
        ),
    ]
