# Generated by Django 3.1.5 on 2021-05-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20210510_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='url',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='serial',
            old_name='url',
            new_name='slug',
        ),
    ]
